"""
SQLAlchemy Declarative Base

All ORM models inherit from this base.
Provides:
- UUID primary keys
- created_at / updated_at timestamps (auto-managed)
- soft delete support (deleted_at)
- to_dict() helper for serialization

Design decisions:
- UUID PKs prevent enumeration attacks and support distributed inserts
- Timestamps use server_default for DB-side consistency
- Soft delete preserves audit history (GDPR compliance consideration)
- Abstract base means no 'base' table is created
"""

import uuid
from datetime import datetime
from typing import Any, Optional

from sqlalchemy import DateTime, text
from sqlalchemy.dialects.postgresql import UUID
from sqlalchemy.orm import DeclarativeBase, Mapped, mapped_column


class Base(DeclarativeBase):
    """
    Abstract declarative base for all TokenTax ORM models.
    All models must inherit from this class.
    """

    # Tell SQLAlchemy not to create a table for this base class
    __abstract__ = True

    # ── Primary Key ───────────────────────────────────────
    # UUID generated by PostgreSQL (gen_random_uuid) for distributed safety
    id: Mapped[uuid.UUID] = mapped_column(
        UUID(as_uuid=True),
        primary_key=True,
        server_default=text("gen_random_uuid()"),
        index=True,
    )

    # ── Timestamps ────────────────────────────────────────
    created_at: Mapped[datetime] = mapped_column(
        DateTime(timezone=True),
        server_default=text("CURRENT_TIMESTAMP"),
        nullable=False,
    )

    updated_at: Mapped[datetime] = mapped_column(
        DateTime(timezone=True),
        server_default=text("CURRENT_TIMESTAMP"),
        onupdate=text("CURRENT_TIMESTAMP"),
        nullable=False,
    )

    # ── Soft Delete ───────────────────────────────────────
    # None = active record, datetime = soft-deleted
    deleted_at: Mapped[Optional[datetime]] = mapped_column(
        DateTime(timezone=True),
        nullable=True,
        default=None,
    )

    def to_dict(self) -> dict[str, Any]:
        """Convert model instance to dictionary."""
        return {
            col.name: getattr(self, col.name)
            for col in self.__table__.columns
        }

    @property
    def is_deleted(self) -> bool:
        """Check if this record has been soft-deleted."""
        return self.deleted_at is not None
